# nice_view is stock, nice_epaper is custom
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_epaper
    # snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_epaper
  - board: nice_nano_v2
    shield: settings_reset
